FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY ./Warehouse.Contracts/*.csproj ./Warehouse.Contracts/
COPY ./Warehouse.Components/*.csproj ./Warehouse.Components/
COPY ./Warehouse.Startup/*.csproj ./Warehouse.Startup/
RUN dotnet restore -r linux-musl-x64 ./Warehouse.Startup/Warehouse.Startup.csproj 

COPY . .
RUN dotnet publish -c Release -o /app -r linux-musl-x64 --no-restore ./Warehouse.Startup/Warehouse.Startup.csproj 

FROM masstransit/platform:7.1.6
WORKDIR /app
COPY --from=build /app ./
