FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY ./Sample.Contracts/*.csproj ./Sample.Contracts/
COPY ./Warehouse.Contracts/*.csproj ./Warehouse.Contracts/
COPY ./Sample.Components/*.csproj ./Sample.Components/
COPY ./Sample.Startup/*.csproj ./Sample.Startup/
RUN dotnet restore -r linux-musl-x64 ./Sample.Startup/Sample.Startup.csproj 

COPY . .
RUN dotnet publish -c Release -o /app -r linux-musl-x64 --no-restore ./Sample.Startup/Sample.Startup.csproj 

FROM masstransit/platform:7.1.5
WORKDIR /app
COPY --from=build /app ./
