FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

COPY ./Sample.Contracts/*.csproj ./Sample.Contracts/
COPY ./Warehouse.Contracts/*.csproj ./Warehouse.Contracts/
COPY ./Sample.Components/*.csproj ./Sample.Components/
COPY ./Sample.Api/*.csproj ./Sample.Api/
RUN dotnet restore ./Sample.Api/Sample.Api.csproj 

COPY . .
RUN dotnet publish -c Release -o /app --no-restore ./Sample.Api/Sample.Api.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Sample.Api.dll"]
